// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD70ydp8EJPiiHwA-wIIWSU0xgazLkqJ3U',
    appId: '1:857991176170:web:7b83996adfc083144d1c93',
    messagingSenderId: '857991176170',
    projectId: 'registrationapp-5bf7b',
    authDomain: 'registrationapp-5bf7b.firebaseapp.com',
    storageBucket: 'registrationapp-5bf7b.appspot.com',
    measurementId: 'G-1PWCZFTY7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA03q7FVcpEb0NsHO0vGIOdY4TOwb0F1vo',
    appId: '1:857991176170:android:1853edc4a12c924b4d1c93',
    messagingSenderId: '857991176170',
    projectId: 'registrationapp-5bf7b',
    storageBucket: 'registrationapp-5bf7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaqoQqlF70bw346G6VQJYNxhLKc6gg4ak',
    appId: '1:857991176170:ios:dc5745e917ec74504d1c93',
    messagingSenderId: '857991176170',
    projectId: 'registrationapp-5bf7b',
    storageBucket: 'registrationapp-5bf7b.appspot.com',
    iosBundleId: 'com.example.resistrationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaqoQqlF70bw346G6VQJYNxhLKc6gg4ak',
    appId: '1:857991176170:ios:dc5745e917ec74504d1c93',
    messagingSenderId: '857991176170',
    projectId: 'registrationapp-5bf7b',
    storageBucket: 'registrationapp-5bf7b.appspot.com',
    iosBundleId: 'com.example.resistrationFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD70ydp8EJPiiHwA-wIIWSU0xgazLkqJ3U',
    appId: '1:857991176170:web:1d1171ce1585e7d04d1c93',
    messagingSenderId: '857991176170',
    projectId: 'registrationapp-5bf7b',
    authDomain: 'registrationapp-5bf7b.firebaseapp.com',
    storageBucket: 'registrationapp-5bf7b.appspot.com',
    measurementId: 'G-X8W0WWK1K4',
  );
}
